### ISSUE TITLE
Will not work with QGIS 3.12 Bucuresti & ECLIPSE

### ISSUE THREAD

**Issue by oddvardm** [sourcepole/qgis-remote-debug#10]
I have configured QGIS & Eclipse with the following (all latest releases) plugins:

1. QGIS - Remote Debugger Plugin
2. Eclipse - PyDev Plugin
3. QGIS - Plugin Builder
4. QGIS - Plugin Reloader

I used the Plugin Builder to create a test plugin: MyTest. All loaded fine and works in QGIS.
The Problem start when I want to intercept the MyTest code in Eclipse.
I started the PyDev remote debugging server in Eclipse and it start up fine with port 5678 (default)
Started QGIS and connected to Eclipse/PyDev: 2020-06-14T20:50:57     INFO    RemoteDebug : Debugging connection activated
In Eclipse I set breakpoint in my MyTest.py file.
Start (& reload) MyTest plugin i QGIS and no breakpoint is detected. MyTest plugin just starts up with no breakpoint stop. This is by the book https://www.sigterritoires.fr/index.php/en/how-to-set-up-eclipse-to-develop-qgis-scripts-or-plugins/ (you left out packages in python https://www.pydev.org/manual_adv_remote_debugger.html) and all seems to work fine. But it does not.  Help needed :-/
[Warnings.txt](https://github.com/sourcepole/qgis-remote-debug/files/4777050/Warnings.txt)

**Comment by oddvardm** [comment]
After some more back and fourth the python console show this error when I connect:

filename: C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\pydevd_file_utils.py
drive: C:\
parts: ['progra~1', 'qgis3~1.12', 'apps', 'python37', 'lib', 'site-packages', 'pydevd_file_utils.py']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find: progra~1 in C:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find: progra~1 in C:\

Maybe an environment fault?

**Comment by oddvardm** [comment]
Changed PYTHONPATH to C:\OSGEO4W\bla..bla so no spaces in path. Now no errors in python console when I start remote debugger. But still not working.

![eclipse](https://user-images.githubusercontent.com/49911978/84651527-678c4080-af0a-11ea-8150-b7b879bb3304.png)

**Comment by cefect** [comment]
I landed here thinking I had similar issues... here's what worked for me:
1) when adding your 'pydevd.py' folder path to QGIS's environment variable for PYTHONPATH, ensure you kick it off w/ a semicolon
2) when launching the RemoteDebug plugin, ensure the 'pydevd' path shown is to the folder containing pydeved.py, not pydevd.py itself.

QGIS 3.12
pydev.core_8.0.1.202011071328
